# Generated by Django 4.2.3 on 2024-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_commandhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("address", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("occupation", models.CharField(max_length=100)),
            ],
        ),
    ]
